name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    env:
       app_name: app_${RUNNER_OS}_ver.${GITHUB_RUN_NUMBER}
    steps:
      - uses: actions/checkout@v3
      - name: build hello world
        run: |
          g++ main.cpp -o ${{ env.app_name }}
          
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: my_app_ubuntu
          path: app_**
          retention-days: 1
          

  fail:
    if: failure()
    runs-on: ubuntu-latest
    needs: [build_ubuntu]
    steps:
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          message: |
            Что-то пошло не так
            ${{ github.actor }} created commit: 
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            
  success:
    if: success()
    runs-on: ubuntu-latest
    needs: [build_ubuntu]
    steps:
      - name: send telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          message: |
            Все ОК
            ${{ github.actor }} created commit: 
            Commit message: ${{ github.event.commits[0].message }}
            Repository: ${{ github.repository }}
            
