name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          message: |
            Автор: ${{ github.actor }}
            Последний коммит: ${{ github.event.commits[0].message }}
            Куда: ${{ github.repository }}
            Коммит: https://github.com/${{ github.repository }}/commit/${{github.sha}}
            
            
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: build
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2



  build_exe:
    name: Build Exe File
    runs-on: ubuntu-latest
    needs: flake8-lint
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            pytest
            pytest-mock
            Eel
      - name: Package Application
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: ./

      - uses: actions/upload-artifact@v2
        with:
          name: my-app
          path: ./dist/windows

  on_finish:
    needs: build_exe
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:

      - name: Success message
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          message: Все ОК
          document: results.zip

      - name: Failure message
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          message: Что-то пошло не так(
