name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_TO }}
          token: ${{ secrets.TG_TOKEN }}
          message: |
            ${{ github.actor }} Последний коммит:
            ${{ github.event.commits[0].message }}
            Куда?: ${{ github.repository }}
            Коммит: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: build
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2




  third-job:
    runs-on: ubuntu-latest
    name: slave
    needs: flake8-lint
    if: ${{ always() }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - uses: BSFishy/pip-action@v1
        with:
          packages: |
            numpy
            matplotlib
            sklearn
            scikit-image
            torch
      - run: python IOR_Lab2.ipynb
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: results
          path: ${{runner.workspace}}/devops/result.txt
          retention-days: 1
      - uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          document: ${{runner.workspace}}/devops/result.txt
          message: |
            artifacts
      - run: pwd
      - run: ls

  on_finish:
    needs: third-job
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:

      - name: Success message
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          message: Все ОК
          document: results.zip

      - name: Failure message
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          message: Что-то пошло не так(
