name: telegram message
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: send telegram message on push
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          message: |
            Автор: ${{ github.actor }}
            Последний коммит: ${{ github.event.commits[0].message }}
            Куда: ${{ github.repository }}
            Коммит: https://github.com/${{ github.repository }}/commit/${{github.sha}}
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    needs: build
    steps:
      - name: Check out source repository
        uses: actions/checkout@v2
      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
      - name: flake8 Lint
        uses: py-actions/flake8@v2




  

  on_finish:
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:

      - name: Success message
        if: ${{ success() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          message: Все ОК
          document: results.zip

      - name: Failure message
        if: ${{ failure() }}
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          message: Что-то пошло не так(
