name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -c "import sys; print(sys.version)"
          python -m pip install --upgrade pip
          python main.py
  
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3


  telegram_success:
    runs-on: ubuntu-latest
    needs: [ push_to_registry ]
    steps:
      - name: send message
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          message: |
            Все ОК
            Repository: ${{ github.repository }}
            Commit message: ${{ github.event.commits[0].message }}
            by: ${{ github.actor }}
  
  telegram_fail:
    if: failure() 
    runs-on: ubuntu-latest
    needs: [ push_to_registry ]
    steps:
      - name: send message
        uses: "appleboy/telegram-action@master"
        with:
          to: ${{ secrets.TG_ID }}
          token: ${{ secrets.TG_TOKEN }}
          message: |
            Что-то пошло не так
            Repository: ${{ github.repository }}
            Commit message: ${{ github.event.commits[0].message }}
            bad human: ${{ github.actor }}
